39 user info api
4-Every1/Jaximus pull request #40
Opened 2022-03-29 23:44 UTC by flower1465

프로필 들어갔을 시 나오는 유저 정보 조회 API 입니다.

확인해주세요

2022-03-29 23:55 UTC, Sonchaegeon requested changes

2022-03-29 23:55 UTC, Sonchaegeon commented on src/infrastructure/repositories/user.repository.ts
> +      .groupBy('user.name')
group by를 user name으로 하는 이유가 있을까요? user.id가 나아 보입니다.
left join의 이유? inner join이 나아 보입니다.

2022-03-29 23:55 UTC, Sonchaegeon commented on src/usecase/user/user-info.ts
> +    const user = this.userRepository.findOne(userId);
이런식이면 select 2번 드갑니다 ㅠㅠ
이 줄 없애고 밑에 userInfo로 exception handling ㄱㄱ

2022-03-29 23:55 UTC, flower1465 commented on src/usecase/user/user-info.ts
> +    const user = this.userRepository.findOne(userId);
옹 좋습니다

2022-03-30 00:00 UTC, Sonchaegeon approved these changes
LGTM :)

2022-03-30 00:01 UTC, merged